apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp1-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name:  nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-2
          image: nginx